include:
  - template: Security/Container-Scanning.gitlab-ci.yml

container_scanning:
  stage: container-scan
  when: on_success
  variables:
    CS_REGISTRY_USER: $CI_REGISTRY_USER
    CS_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
    SECURE_LOG_LEVEL: info
    GIT_STRATEGY: clone
    CS_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    CS_IGNORE_UNFIXED: "true"
  allow_failure: true
  artifacts:
    paths:
      - gl-container-scanning-report.json
    reports:
      sast: gl-container-scanning-report.json
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_TAG != "null"
      when: never
