# Verify if Jira Ticket Matches the Name of the Merge Request
variables:
  JIRA_PASSWORD: <insert jira password here>
  JIRA_USERNAME: <insert jira username here>
  JIRA_URL: <insert jira url here>
check_jira_ticket:
  image: python:3.11-alpine
  stage: verify-jira-ticket
  when: manual
  before_script:
    - TXT_PINK="\e[31m" && TXT_Y="\e[93m"
    - apk add -q curl jq gettext
    - pip3 install -q requests==2.28.1
    - echo -e "${TXT_PINK}Verifying if Merge Request Title Matches a Jira Ticket,"
    - echo -e "${TXT_PINK}Please make sure the Ticket number is in and at the start of the Merge Title like so; ${TXT_Y}OSP-####:"
  script:
    - export JIRA_TICKET="$(echo $CI_MERGE_REQUEST_TITLE | cut -d ":" -f1 | tr -d " \t" )"
    - echo "$JIRA_TICKET"
    - python3 scripts/validate_jira.py "$JIRA_TICKET"
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != /^(bugfix|devops)(\/).*$/
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(bugfix|devops)(\/).*$/
      when: never
      allow_failure: true
    - if: $CI_COMMIT_TAG != "null"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
